export const SET_TABLE_CELL = "SET_TABLE_CELL"
export const SET_TABLE_ACTIVE_CELL = "SET_TABLE_ACTIVE_CELL"
// export const GET_CELLS_DATA = "GET_CELLS_DATA"
export const SHOW_URL_PREVIEW = "SHOW_URL_PREVIEW"
export const HIDE_URL_PREVIEW = "HIDE_URL_PREVIEW"

